name: cafe_mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rive: ^0.13.12
  dio: ^5.5.0+1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  path_provider: ^2.1.3
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  emoji_picker_flutter: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
